ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-alpine
RUN apk add --no-cache sqlite
WORKDIR /app
COPY package.json package-lock.json .npmrc ./
RUN npm ci --legacy-peer-deps
COPY . .
RUN npm run build
CMD ["npm", "run", "test:unit"]
